# -*- coding: utf-8 -*-
"""explore_ml_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x0itBV4ySaByVYCLxAm7mp_uLiuo3BTR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#loading the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
dataset1 = pd.read_csv('Churn_Modelling.csv')

#to load the data
dataset.head(10)

dataset = dataset.iloc[:,3:]

#to check for missing values
dataset.isnull().sum

#to check rows and coloumns of the dataset
np.shape(dataset)

dataset.iloc[:,1]

#encoding categorical data
dataset_country = dataset.iloc[:,1]
def encode_country(country):
  if country== 'France':
    return 0
  elif country=='Spain' :
    return 1
  elif country=='Germany' :
    return 2
  
dataset_country = list(map(encode_country,dataset_country))

dataset.iloc[:,1]

#splitting the dataset into ytrainset and test set
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

from sklearn.model_selection import train_test_split as tts 
x_train, x_test, y_train, y_test = tts(x,y,test_size=0.3,random_state=0)

print(np.shape(x_train))
print(np.shape(x_test))

dataset.describe()

from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
x_train.age = np.array(x_train[:,3])
x_train[:,3] = std_scaler.fit_transform(x_train.age)

#def scale_age(age):




dataset.columns

#dataset_age = dataset['Age']
dataset.age.head
